export const CATEGORIES = {
  frontend: [
    { title: "JavaScript", fileName: "JavaScript" },
    { title: "HTML", fileName: "HTML" },
    { title: "CSS", fileName: "CSS" },
    { title: "TypeScript", fileName: "TypeScript" },
    { title: "React", fileName: "React" },
    { title: "Angular", fileName: "Angular" },
    { title: "Vue", fileName: "Vue" },
    { title: "Sass", fileName: "Sass" },
    { title: "LESS", fileName: "LESS" },
  ],
  backend: [
    { title: "Java", fileName: "Java" },
    { title: "Spring", fileName: "Spring" },
    { title: "Python", fileName: "Python" },
    { title: "Django", fileName: "Django" },
    { title: "Node.js", fileName: "Nodejs" },
    { title: "Express.js", fileName: "Expressjs" },
    { title: "Ruby", fileName: "Ruby" },
    { title: "PHP", fileName: "PHP" },
    { title: "Laravel", fileName: "Laravel" },
  ],
  mobile: [
    { title: "Swift", fileName: "Swift" },
    { title: "Kotlin", fileName: "Kotlin" },
    { title: "Android", fileName: "Android" },
    { title: "React Native", fileName: "React-Native" },
    { title: "Flutter", fileName: "Flutter" },
    { title: "Xamarin", fileName: "Xamarin" },
  ],
  database: [
    { title: "SQL", fileName: "SQL" },
    { title: "MySQL", fileName: "MySQL" },
    { title: "PostgreSQL", fileName: "PostgreSQL" },
    { title: "MongoDB", fileName: "MongoDB" },
    { title: "Firebase", fileName: "Firebase" },
    { title: "SQLite", fileName: "SQLite" },
    { title: "Oracle", fileName: "Oracle" },
    { title: "Redis", fileName: "Redis" },
  ],
  devOps: [
    { title: "Docker", fileName: "Docker" },
    { title: "Kubernetes", fileName: "Kubernetes" },
    { title: "Jenkins", fileName: "Jenkins" },
    { title: "Git", fileName: "Git" },
    { title: "GitHub", fileName: "GitHub" },
    { title: "GitLab", fileName: "GitLab" },
    { title: "Bitbucket", fileName: "Bitbucket" },
    { title: "Ansible", fileName: "Ansible" },
    { title: "Puppet", fileName: "Puppet" },
  ],
  machineLearning: [
    { title: "Python", fileName: "Python" },
    { title: "TensorFlow", fileName: "TensorFlow" },
    { title: "PyTorch", fileName: "PyTorch" },
    { title: "Scikit learn", fileName: "Scikit-learn" },
    { title: "Keras", fileName: "Keras" },
    { title: "OpenCV", fileName: "OpenCV" },
  ],
  gameDevelopment: [
    { title: "Unity", fileName: "Unity" },
    { title: "C#", fileName: "C#" },
    { title: "Unreal Engine", fileName: "Unreal-Engine" },
    { title: "C++", fileName: "C++" },
    { title: "Godot", fileName: "Godot" },
  ],
  cybersecurity: [
    { title: "Python", fileName: "Python" },
    { title: "Wireshark", fileName: "Wireshark" },
    { title: "Metasploit", fileName: "Metasploit" },
    { title: "Burp Suite", fileName: "Burp-Suite" },
    { title: "Snort", fileName: "Snort" },
    { title: "OWASP ZAP", fileName: "OWASP-ZAP" },
  ],
};

export const CATEGORYS_PATH = {
  JavaScript: "./images/languages/JavaScript-logo.png",
  HTML: "./images/languages/HTML-logo.png",
  CSS: "./images/languages/CSS-logo.png",
  TypeScript: "./images/languages/TypeScript-logo.png",
  React: "./images/languages/React-logo.png",
  Angular: "./images/languages/Angular-logo.png",
  Vue: "./images/languages/Vue-logo.png",
  Sass: "./images/languages/Sass-logo.png",
  LESS: "./images/languages/LESS-logo.png",
  Java: "./images/languages/Java-logo.png",
  Spring: "./images/languages/Spring-logo.png",
  Python: "./images/languages/Python-logo.png",
  Django: "./images/languages/Django-logo.png",
  "Node.js": "./images/languages/Nodejs-logo.png",
  "Express.js": "./images/languages/Expressjs-logo.png",
  Ruby: "./images/languages/Ruby-logo.png",
  PHP: "./images/languages/PHP-logo.png",
  Laravel: "./images/languages/Laravel-logo.png",
  Swift: "./images/languages/Swift-logo.png",
  Kotlin: "./images/languages/Kotlin-logo.png",
  Android: "./images/languages/Android-logo.png",
  "React Native": "./images/languages/React-Native-logo.png",
  Flutter: "./images/languages/Flutter-logo.png",
  Xamarin: "./images/languages/Xamarin-logo.png",
  SQL: "./images/languages/SQL-logo.png",
  MySQL: "./images/languages/MySQL-logo.png",
  PostgreSQL: "./images/languages/PostgreSQL-logo.png",
  MongoDB: "./images/languages/MongoDB-logo.png",
  Firebase: "./images/languages/Firebase-logo.png",
  SQLite: "./images/languages/SQLite-logo.png",
  Oracle: "./images/languages/Oracle-logo.png",
  Redis: "./images/languages/Redis-logo.png",
  Docker: "./images/languages/Docker-logo.png",
  Kubernetes: "./images/languages/Kubernetes-logo.png",
  Jenkins: "./images/languages/Jenkins-logo.png",
  Git: "./images/languages/Git-logo.png",
  GitHub: "./images/languages/GitHub-logo.png",
  GitLab: "./images/languages/GitLab-logo.png",
  Bitbucket: "./images/languages/Bitbucket-logo.png",
  Ansible: "./images/languages/Ansible-logo.png",
  Puppet: "./images/languages/Puppet-logo.png",
  TensorFlow: "./images/languages/TensorFlow-logo.png",
  PyTorch: "./images/languages/PyTorch-logo.png",
  "Scikit learn": "./images/languages/Scikit-learn-logo.png",
  Keras: "./images/languages/Keras-logo.png",
  OpenCV: "./images/languages/OpenCV-logo.png",
  Unity: "./images/languages/Unity-logo.png",
  "C#": "./images/languages/C#-logo.png",
  "Unreal Engine": "./images/languages/Unreal-Engine-logo.png",
  "C++": "./images/languages/C++-logo.png",
  Godot: "./images/languages/Godot-logo.png",
  "OWASP ZAP": "./images/languages/OWASP-ZAP-logo.png",
  Wireshark: "./images/languages/Wireshark-logo.png",
  Metasploit: "./images/languages/Metasploit-logo.png",
  "Burp Suite": "./images/languages/Burp-Suite-logo.png",
  Snort: "./images/languages/Snort-logo.png",
};
